apiVersion: v1
kind: Service
metadata:
  name: nginx1
  namespace: cis-app
  labels:
    app: nginx1
    cis.f5.com/as3-tenant: WEB1
    cis.f5.com/as3-app: NGINX1
    cis.f5.com/as3-pool: nginx1_pool
spec:
  selector:
    app: nginx1
  ports:
    - name: nginx1
      protocol: TCP
      port: 80
      targetPort: myhttpport
  type: NodePort

