kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx1-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.23.0",
            "id": "testas3",
            "label": "http",
            "remark": "nginx1 Template",
            "WEB-1": {
                "class": "Tenant",
                "NGINX1": {
                    "class": "Application",
                      "template": "generic",
                      "nginx1_httpvs": {
                        "class": "Service_HTTP",
                        "remark": "nginx1",
                        "virtualAddresses": [
                            "10.10.0.110"
                        ],
                        "pool": "nginx1_pool"
                    },
                    "nginx1_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }

